# Generated by Django 5.2.4 on 2025-07-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for search engines', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='open_graph_meta_description',
            field=models.TextField(blank=True, help_text='Description for social media sharing', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='page_header',
            field=models.CharField(blank=True, help_text='SEO-optimized page header', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_features',
            field=models.JSONField(blank=True, default=list, help_text='List of product features'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tags',
            field=models.CharField(blank=True, help_text='Social media hashtags and tags', max_length=500, null=True),
        ),
    ]
