# Generated by Django 5.2.4 on 2025-07-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_url_product_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='af_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
