# Generated by Django 5.2.4 on 2025-07-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_af_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='af_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
