# Generated by Django 5.2.4 on 2025-08-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_af_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='af_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
