# docker-compose.prod.yml
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=0
    depends_on:
      - redis
    volumes:
      - .staticfiles:/app/staticfiles
      - media_volume:/app/media
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  redis_data:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge